version: '3.7'

services:
  python:
    container_name: python
    build:
      context: .
      dockerfile: DockerFile.python
      args:
        USER: ${USER}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - ${USER_PATH}:/app
    command: sh -c "python -m http.server 8002"
    # command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    networks:
      - dev
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ${USER_PATH}/postgres/pgadmin:/var/lib/pgadmin
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    networks:
      - dev
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${USER_PATH}/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    stdin_open: true
    tty: true
    networks:
      - dev

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ${USER_PATH}/mongo:/data/db
    ports:
      - "27017:27017"
    stdin_open: true
    tty: true
    networks:
      - dev
  mongo_express:
    container_name: mongo-express
    image: mongo-express:latest
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ${ME_CONFIG_OPTIONS_EDITORTHEME}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_MONGODB_PORT: ${ME_CONFIG_MONGODB_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - "8005:8081"
    depends_on:
      - mongo
    stdin_open: true
    tty: true
    networks:
      - dev

networks:
  dev:
    external:
      name: dev