version: '3'

services:
  db:
    container_name: postgres
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: example
    volumes:
      - /home/daniel/Documentos/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    container_name: python
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
