version: '3'

services:
  db_postgres:
    container_name: postgres
    build:
      context: ./postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${USER_PATH}/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db_admin:
    container_name: pgadmin
    build:
      context: ./pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"
  db_mongo:
    container_name: mongo
    build:
      context: ./mongo
    volumes:
      - ${USER_PATH}/mongo:/data/db
    ports:
      - "27017:27017"
  db_mongo_admin:
    container_name: mongo-express
    build:
      context: ./mongo-express
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ${ME_CONFIG_OPTIONS_EDITORTHEME} 
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_MONGODB_PORT: ${ME_CONFIG_MONGODB_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    ports:
      - "8080:8081"
  server_nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ${USER_PATH}/nginx:/usr/share/nginx/html 
    ports:
      - "8081:80"
  server_apache:
    container_name: apache
    build:
      context: ./apache
    volumes:
      - ${USER_PATH}/apache:/usr/local/apache2/htdocs 
    ports:
      - "8082:80"
