version: '3'

services:
  db:
    container_name: postgres
    build:
      context: ./postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /home/daniel/Documentos/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db_admin:
    container_name: pgadmin
    build:
      context: ./pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"
